### ISSUE TITLE
Error in `geom_link()`:

### ISSUE THREAD

**Issue by fhu2008** [thackl/gggenomes#131] opened 2022-11-08 10:45 UTC
Hello, and thanks for an awesome tool!

I have a question regarding geom_link. when  geom_link()  was added, the errores were showed. Could you help me fix this.

Thanks in advance!

----sample data (R.version 4.2.0)

s0 <- tibble(
  seq_id = c("a", "b"),
  length = c(600, 550)
)

g0 <- tibble(
  seq_id = c("a", "a", "b"),
  start = c(50, 350, 80),
  end = c(250, 500, 450)
)

l0 <- tibble(
  seq_id = c("a", "a"),
  start = c(50, 400),
  end = c(250, 480),
  seq_id2 = c("b", "b"),
  start2 = c(80, 350),
  end2 = c(300, 430)
)

p <- gggenomes(genes=g0, seqs=s0, links=l0)
p + 
  geom_seq() +         
  geom_seq_label() +   
  geom_gene() +       

-----ok

when added geom_link()    ,

Error in `geom_link()`:
! Problem while converting geom to grob.
i Error occurred in the 4th layer.
Caused by error in `link_to_poly()`:
! object 'new_data_frame' not found
Run `rlang::last_error()` to see where the error occurred

Backtrace:
  1. base (local) `<fn>`(x)
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_gtable.ggplot_built(data)
  5. ggplot2:::by_layer(...)
 12. ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 13. l$draw_geom(d, layout)
 14. ggplot2 (local) draw_geom(..., self = self)
 15. self$geom$draw_layer(...)
 16. ggplot2 (local) draw_layer(..., self = self)
 17. base::lapply(...)
 18. ggplot2 (local) FUN(X[[i]], ...)
 20. self$draw_panel(data, panel_params, coord, offset = `<dbl>`)
 21. gggenomes (local) draw_panel(..., self = self)
 22. base::lapply(...)
 23. gggenomes (local) FUN(X[[i]], ...)
 24. gggenomes:::link_to_poly(...)
Run `rlang::last_trace()` to see the full context.

**Comment by thackl** [comment] 2022-11-09 09:54
Hi, thanks for reporting. Unfortunately, I cannot reproduce this issue on my system, which makes it a bit tricky to debug. Could you send me the output of `sessionInfo()` after loading `gggenomes`?

**Comment by FWittmers** [comment] 2022-11-09 10:02
Hi, thanks for the swift response. If you still would like me to get you the sessionInfo I can do that, but looks like you know what's going on already. Thanks again!

**Comment by thackl** [comment] 2022-11-09 10:48
Ok, should be fixed by https://github.com/thackl/gggenomes/commit/f70d3fae346d9494f453ddf11f9393a04c649674. Let me know if you still have problems after updating the package.

**Closed by thackl** 2022-11-09 10:48 UTC

**Comment by fhu2008** [comment] 2022-11-09 11:42
It still doesn't work after updating the package., the errors information are the same as before. However,  it works when I change the ggplot2 version from 3.4 to 3.0.0 .
many thanks.

**Comment by FWittmers** [comment] 2022-11-09 11:59
For me reinstalling the package fixed this bug, no need to change my ggplot2 version. Thanks for the quick fix!
